var product =[{
    "id" : 0,
    "title" : "",
    "Price" : "",
    "Description" : "",
    "brand" : "",
    "image" : "https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/No-Image-Placeholder.svg/1665px-No-Image-Placeholder.svg.png",
},
//hyundai
{
    "id" : 1,
    "title" : "Hyundai Alcazar",
    "Price" : "17.74 lakhs",
    "Milage" : "14.2 to 20.4 kmpl",
    "Engine" : "1493 to 1999 cc",
    "Fuel" : "Petrol & Diesel",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "6 & 7 Seater",
    "brand" : "Hyndia",
    "image" : "car/Hyundia/car-1.webp",
},
{
    "id" : 2,
    "title" : "Hyundai Grand i10 Nios",
    "Price" : "6.30 lakhs",
    "Milage" : "25 kmpl",
    "Engine" : "998 to 1197 cc",
    "Fuel" : "Petrol, CNG & Diesel",
    "Transmission" : "Manual & Automatic (AMT)",
    "Seating" : "5 Seater",
    "brand" : "Hyndia",
    "image" : "car/Hyundia/car-2.webp",
},
{
    "id" : 3,
    "title" : "Hyundai Creta",
    "Price" : "12.02 lakhs",
    "Milage" : "17 to 21 kmpl",
    "Engine" : "1353 to 1497 cc",
    "Fuel" : "Petrol & Diesel",
    "Transmission" : "Manual, Clutchless Manual (IMT), Automatic (DCT), Automatic (CVT) & Automatic (TC)",
    "Seating" : "5 Seater",
    "brand" : "Hyndia",
    "image" : "car/Hyundia/car-3.webp",
},
{
    "id" : 4,
    "title" : "Hyundai Verna",
    "Price" : "10.70 lakhs",
    "Milage" : "17.7 to 25 kmpl",
    "Engine" : "998 to 1497 cc",
    "Fuel" : "Petrol & Diesel",
    "Transmission" : "Manual, Automatic (CVT), Automatic (TC) & Automatic (DCT)",
    "Seating" : "5 Seater",
    "brand" : "Hyndia",
    "image" : "car/Hyundia/car-4.webp",
},
{
    "id" : 5,
    "title" : "Hyundai i20",
    "Price" : "8.12 lakhs",
    "Milage" : "19.6 to 25.2 kmpl",
    "Engine" : "998 to 1493 cc",
    "Fuel" : "Petrol & Diesel",
    "Transmission" : "Manual, Clutchless Manual (IMT), Automatic (CVT) & Automatic (DCT)",
    "Seating" : "5 Seater",
    "brand" : "Hyndia",
    "image" : "car/Hyundia/car-5.webp",
},
//mahindra
{
    "id" : 6,
    "title" : "Mahindra Bolero",
    "Price" : "10.55 lakhs",
    "Milage" : "16.7 kmpl",
    "Engine" : "1493 cc",
    "Fuel" : "Diesel",
    "Transmission" : "Manual",
    "Seating" : "7 Seater",
    "brand" : "Mahindra",
    "image" : "car/mahindra/car-1.webp",
},
{
    "id" : 7,
    "title" : "Mahindra Scorpio Classic",
    "Price" : "13.81 lakhs",
    "Milage" : "15 kmpl",
    "Engine" : "2184 cc",
    "Fuel" : "Diesel",
    "Transmission" : "Manual",
    "Seating" : "7 & 9 Seater",
    "brand" : "Mahindra",
    "image" : "car/mahindra/car-2.webp",
},
{
    "id" : 8,
    "title" : "Mahindra Scorpio-N",
    "Price" : "13.45 lakhs",
    "Milage" : "11.67 to 13.67 kmpl",
    "Engine" : "1997 to 2184 cc",
    "Fuel" : "Petrol & Diesel",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "6 & 7 Seater",
    "brand" : "Mahindra",
    "image" : "car/mahindra/car-3.webp",
},
{
    "id" : 9,
    "title" : "Mahindra Thar",
    "Price" : "15.62 lakhs",
    "Milage" : "15.2 kmpl",
    "Engine" : "1997 to 2184 cc",
    "Fuel" : "Petrol & Diesel",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "4 Seater",
    "brand" : "Mahindra",
    "image" : "car/mahindra/car-4.webp",
},
{
    "id" : 10,
    "title" : "Mahindra XUV700",
    "Price" : "15.53 lakhs",
    "Milage" : "15.0 to 17.0 kmpl",
    "Engine" : "1997 to 2184 cc",
    "Fuel" : "Petrol & Diesel",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "5 & 7 Seater",
    "brand" : "Mahindra",
    "image" : "car/mahindra/car-5.webp",
},
//Maruti Suzuki
{
    "id" : 11,
    "title" : "Maruti XL6",
    "Price" : "12.50 lakhs",
    "Milage" : "20.2 to 26.32 km/kg",
    "Engine" : "1462 cc",
    "Fuel" : "Petrol & CNG",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "6 Seater",
    "brand" : "Maruti Suzuki",
    "image" : "car/Maruti Suzuki/car-1.webp",
},
{
    "id" : 12,
    "title" : "Maruti Baleno",
    "Price" : "7.24 lakhs",
    "Milage" : "22.3 to 30.61 km/kg",
    "Engine" : "1197 cc",
    "Fuel" : "Petrol & CNG",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "5 Seater",
    "brand" : "Maruti Suzuki",
    "image" : "car/Maruti Suzuki/car-2.webp",
},
{
    "id" : 13,
    "title" : "Maruti Ciaz",
    "Price" : "9.92 lakhs",
    "Milage" : "20 to 20.6 kmpl",
    "Engine" : "1462 cc",
    "Fuel" : "Petrol",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "5 Seater",
    "brand" : "Maruti Suzuki",
    "image" : "car/Maruti Suzuki/car-3.webp",
},
{
    "id" : 14,
    "title" : "Maruti Swift",
    "Price" : "6.69 lakhs",
    "Milage" : "22.38 to 30.9 km/kg",
    "Engine" : "1197 cc",
    "Fuel" : "Petrol & CNG",
    "Transmission" : "Manual & Automatic (AMT)",
    "Seating" : "5 Seater",
    "brand" : "Maruti Suzuki",
    "image" : "car/Maruti Suzuki/car-4.webp",
},
{
    "id" : 15,
    "title" : "Maruti Dzire",
    "Price" : "7.04 lakhs",
    "Milage" : "23.2 to 24.1 kmpl",
    "Engine" : "1197 cc",
    "Fuel" : "Petrol & CNG",
    "Transmission" : "Manual & Automatic (AMT)",
    "Seating" : "5 Seater",
    "brand" : "Maruti Suzuki",
    "image" : "car/Maruti Suzuki/car-5.webp",
},
{
    "id" : 16,
    "title" : "Maruti S-Cross",
    "Price" : "9.87 lakhs",
    "Milage" : "18.4 to 18.5 kmpl",
    "Engine" : "1462 cc",
    "Fuel" : "Petrol",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "5 Seater",
    "brand" : "Maruti Suzuki",
    "image" : "car/Maruti Suzuki/car-6.webp",
},
{
    "id" : 17,
    "title" : "Maruti Brezza",
    "Price" : "8.93 lakhs",
    "Milage" : "19.8 to 19.9 kmpl",
    "Engine" : "1462 cc",
    "Fuel" : "Petrol",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "5 Seater",
    "brand" : "Maruti Suzuki",
    "image" : "car/Maruti Suzuki/car-7.webp",
},
{
    "id" : 18,
    "title" : "Maruti Wagon R",
    "Price" : "6.17 lakhs",
    "Milage" : "23.5 to 34 kmpl",
    "Engine" : "998 to 1197 cc",
    "Fuel" : "Petrol & CNG",
    "Transmission" : "Manual & Automatic (AMT)",
    "Seating" : "5 Seater",
    "brand" : "Maruti Suzuki",
    "image" : "car/Maruti Suzuki/car-8.webp",
},
//tata
{
    "id" : 19,
    "title" : "Tata Altroz",
    "Price" : "7.08 lakhs",
    "Milage" : "18.33 to 23 kmpl",
    "Engine" : "1199 to 1497 cc",
    "Fuel" : "Petrol & Diesel",
    "Transmission" : "Manual & Automatic (DTC)",
    "Seating" : "5 Seater",
    "brand" : "Tata",
    "image" : "car/tata/car-1.webp",
},
{
    "id" : 20,
    "title" : "Tata Punch",
    "Price" : "6.70 lakhs",
    "Milage" : "18.8 to 18.9 kmpl",
    "Engine" : "1199 cc",
    "Fuel" : "Petrol",
    "Transmission" : "Manual & Automatic (AMT)",
    "Seating" : "5 Seater",
    "brand" : "Tata",
    "image" : "car/tata/car-2.webp",
},
{
    "id" : 21,
    "title" : "Tata Safari",
    "Price" : "17.56 lakhs",
    "Milage" : "14 to 16.1 kmpl",
    "Engine" : "1956 cc",
    "Fuel" : "Diesel",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "6 & 7 Seater",
    "brand" : "Tata",
    "image" : "car/tata/car-3.webp",
},
{
    "id" : 22,
    "title" : "Tata Harrier",
    "Price" : "16.80 lakhs",
    "Milage" : "14.6 to 16.3 kmpl",
    "Engine" : "1956 cc",
    "Fuel" : "Diesel",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "5 Seater",
    "brand" : "Tata",
    "image" : "car/tata/car-4.webp",
},
{
    "id" : 23,
    "title" : "Tata Nexon",
    "Price" : "8.54 lakhs",
    "Milage" : "16.3 to 22 kmpl",
    "Engine" : "1199 to 1497 cc",
    "Fuel" : "Petrol & Diesel",
    "Transmission" : "Manual & Automatic (AMT)",
    "Seating" : "5 Seater",
    "brand" : "Tata",
    "image" : "car/tata/car-5.webp",
},
//toyota
{
    "id" : 24,
    "title" : "Toyota Fortuner",
    "Price" : "36.03 lakhs",
    "Milage" : "10 to 14.4 kmpl",
    "Engine" : "2694 to 2755 cc",
    "Fuel" : "Petrol & Diesel",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "7 Seater",
    "brand" : "Toyota",
    "image" : "car/toyota/car-1.webp",
},
{
    "id" : 25,
    "title" : "Toyota Glanza",
    "Price" : "7.34 lakhs",
    "Milage" : "22.3 to 30.61 km/kg",
    "Engine" : "1197 cc",
    "Fuel" : "Petrol & CNG",
    "Transmission" : "Manual & Automatic (AMT)",
    "Seating" : "5 Seater",
    "brand" : "Toyota",
    "image" : "car/toyota/car-2.webp",
},
{
    "id" : 26,
    "title" : "Toyota Innova Crysta",
    "Price" : "20.13 lakhs",
    "Milage" : "10.2 to 15.6 kmpl",
    "Engine" : "2393 to 2694 cc",
    "Fuel" : "Petrol & Diesel",
    "Transmission" : "Manual & Automatic (TC)",
    "Seating" : "7 & 8 Seater",
    "brand" : "Toyota",
    "image" : "car/toyota/car-3.webp",
},
{
    "id" : 27,
    "title" : "Toyota Urban Cruiser Hyryder",
    "Price" : "11.62 lakhs",
    "Milage" : "20.58 to 27.97 kmpl",
    "Engine" : "1462 to 1490 cc",
    "Fuel" : "Mild Hybrid(Electric + Petrol), Hybrid (Electric + Petrol) & CNG",
    "Transmission" : "Manual, Automatic (TC) & Automatic (CVT)",
    "Seating" : "5 Seater",
    "brand" : "Toyota",
    "image" : "car/toyota/car-4.webp",
},
]